id = "io.limao996.hoohoolib"
name = "齁哦哦文库"
author = "limao996"
categories = ["novel","others"]
summary = "老司机数据源合集"
is_nsfw = true

description = """
本插件整合了多个老司机数据源。

标注🛩️的数据源皆要挂VPN

所有数据仅供学习交流使用，请遵守相关法律法规。
"""

target_api = 2
languages = ["zh","ja","ko"]
copyright = "© 2026 limao996"

[release]
version_name = "1.0.2"
version_code = 3
changelog = """
1. 增加正文图片的访问超时时长
2. 解决可能存在的端口冲突
3. 移除对象缓存
4. 修复若干bug
"""

[release.download]
file = "plugin-debug.apk.lnrp"
output_file = "plugin-debug.apk.lnrp"
sha1 = "21cc65cb8959c792038202b496e474aafbfa9ba0"

[privacy]
data_keys = ["network_access"]
notes = ""

[links]
homepage = "https://github.com/limao996"
repository = "https://github.com/limao996/LightNovelReaderPlugin-HoohooLib.git"

[assets]
icon = "icon.png"
banner = "banner.png"
screenshots = ["screenshot_1.jpg","screenshot_2.jpg","screenshot_3.jpg","screenshot_4.jpg","screenshot_5.jpg"]
